version: '3.1'

services:

  db_labtec:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: labtec
      POSTGRES_DB: labtec
    ports:
      - 5401:5432
    volumes:
      - db_labtec:/var/lib/postgresql/data
    
volumes:
  db_labtec: